-- =====================================================================
-- GSB-CR : création des tables (schéma GSB)
-- SQL compatible Oracle 19c (voir docs/decisions.md D-11)
-- Conventions : tables au singulier en MAJUSCULES, colonnes préfixées
--               par le trigramme de la table, contraintes nommées.
-- =====================================================================
whenever sqlerror exit failure

-- ---------------------------------------------------------------------
-- 1. ORGANISATION : secteurs, régions, profils, collaborateurs
-- ---------------------------------------------------------------------

create table SECTEUR (
    sec_code        varchar2(1 char)   constraint pk_secteur primary key,
    sec_libelle     varchar2(30 char)  not null,
    constraint uq_secteur_libelle unique (sec_libelle)
);

create table REGION (
    reg_code        varchar2(3 char)   constraint pk_region primary key,
    reg_nom         varchar2(50 char)  not null,
    sec_code        varchar2(1 char)   not null
                    constraint fk_region_secteur references SECTEUR (sec_code),
    constraint uq_region_nom unique (reg_nom)
);

-- Profils applicatifs : VIS (visiteur), DEL (délégué), RES (responsable), ADM (administrateur)
create table PROFIL (
    pro_code        varchar2(3 char)   constraint pk_profil primary key,
    pro_libelle     varchar2(30 char)  not null
);

create table COLLABORATEUR (
    col_matricule           varchar2(10 char)   constraint pk_collaborateur primary key,
    col_nom                 varchar2(50 char)   not null,
    col_prenom              varchar2(50 char)   not null,
    col_adresse             varchar2(100 char),
    col_cp                  varchar2(5 char),
    col_ville               varchar2(50 char),
    col_telephone           varchar2(20 char),
    col_email               varchar2(100 char),
    col_date_embauche       date                not null,
    col_date_depart         date,
    -- Authentification (mot de passe haché PBKDF2, jamais en clair)
    col_login               varchar2(30 char)   not null,
    col_mdp                 varchar2(200 char)  not null,
    col_mdp_a_changer       char(1)             default 'O' not null,
    col_nb_echecs           number(2)           default 0 not null,
    col_verrouille          char(1)             default 'N' not null,
    col_derniere_connexion  timestamp,
    constraint uq_collaborateur_login unique (col_login),
    constraint ck_collab_depart      check (col_date_depart is null or col_date_depart >= col_date_embauche),
    constraint ck_collab_mdp_changer check (col_mdp_a_changer in ('O', 'N')),
    constraint ck_collab_verrouille  check (col_verrouille in ('O', 'N')),
    constraint ck_collab_nb_echecs   check (col_nb_echecs >= 0)
);

-- Historique des affectations (profil + région ou secteur) : on garde la trace
-- de l'évolution de chaque collaborateur, une même région pouvant revenir.
create table AFFECTATION (
    aff_id          number generated by default as identity constraint pk_affectation primary key,
    col_matricule   varchar2(10 char)  not null
                    constraint fk_affectation_collab references COLLABORATEUR (col_matricule),
    pro_code        varchar2(3 char)   not null
                    constraint fk_affectation_profil references PROFIL (pro_code),
    reg_code        varchar2(3 char)
                    constraint fk_affectation_region references REGION (reg_code),
    sec_code        varchar2(1 char)
                    constraint fk_affectation_secteur references SECTEUR (sec_code),
    aff_date_debut  date               not null,
    aff_date_fin    date,
    constraint ck_affectation_dates check (aff_date_fin is null or aff_date_fin >= aff_date_debut),
    -- Visiteur / délégué : rattaché à une région ; responsable : à un secteur ; admin : à rien
    constraint ck_affectation_rattachement check (
           (pro_code in ('VIS', 'DEL') and reg_code is not null and sec_code is null)
        or (pro_code = 'RES'           and sec_code is not null and reg_code is null)
        or (pro_code = 'ADM'           and reg_code is null     and sec_code is null))
);

-- Une seule affectation en cours par collaborateur
create unique index ux_affectation_en_cours
    on AFFECTATION (case when aff_date_fin is null then col_matricule end);
-- Un seul délégué en cours par région
create unique index ux_affectation_delegue
    on AFFECTATION (case when aff_date_fin is null and pro_code = 'DEL' then reg_code end);
-- Un seul responsable en cours par secteur
create unique index ux_affectation_responsable
    on AFFECTATION (case when aff_date_fin is null and pro_code = 'RES' then sec_code end);
create index ix_affectation_collab on AFFECTATION (col_matricule);

-- ---------------------------------------------------------------------
-- 2. PRATICIENS
-- ---------------------------------------------------------------------

create table TYPE_PRATICIEN (
    typ_code        varchar2(2 char)   constraint pk_type_praticien primary key,
    typ_libelle     varchar2(50 char)  not null,
    typ_lieu        varchar2(50 char)  not null
);

create table PRATICIEN (
    pra_num             number generated by default as identity constraint pk_praticien primary key,
    pra_nom             varchar2(50 char)  not null,
    pra_prenom          varchar2(50 char)  not null,
    pra_adresse         varchar2(100 char),
    pra_cp              varchar2(5 char),
    pra_ville           varchar2(50 char),
    pra_telephone       varchar2(20 char),
    pra_email           varchar2(100 char),
    -- Coefficient de notoriété : donnée achetée à des organismes spécialisés
    pra_coef_notoriete  number(6, 2),
    typ_code            varchar2(2 char)   not null
                        constraint fk_praticien_type references TYPE_PRATICIEN (typ_code),
    pra_actif           char(1)            default 'O' not null,
    pra_date_maj        date               default sysdate not null,
    constraint ck_praticien_notoriete check (pra_coef_notoriete is null or pra_coef_notoriete >= 0),
    constraint ck_praticien_actif     check (pra_actif in ('O', 'N'))
);
create index ix_praticien_nom on PRATICIEN (pra_nom, pra_prenom);

create table SPECIALITE (
    spe_code        varchar2(5 char)   constraint pk_specialite primary key,
    spe_libelle     varchar2(60 char)  not null
);

-- Spécialités d'un praticien : diplôme le plus haut + coefficient de prescription
create table POSSEDER (
    pra_num                 number             not null
                            constraint fk_posseder_praticien references PRATICIEN (pra_num) on delete cascade,
    spe_code                varchar2(5 char)   not null
                            constraint fk_posseder_specialite references SPECIALITE (spe_code),
    pos_diplome             varchar2(60 char),
    pos_coef_prescription   number(6, 2),
    constraint pk_posseder primary key (pra_num, spe_code),
    constraint ck_posseder_coef check (pos_coef_prescription is null or pos_coef_prescription >= 0)
);

-- Portefeuille : quel visiteur suit quel praticien, avec historique (turn-over)
create table PORTEFEUILLE (
    pra_num             number             not null
                        constraint fk_portefeuille_praticien references PRATICIEN (pra_num),
    col_matricule       varchar2(10 char)  not null
                        constraint fk_portefeuille_collab references COLLABORATEUR (col_matricule),
    ptf_date_debut      date               not null,
    ptf_date_fin        date,
    constraint pk_portefeuille primary key (pra_num, ptf_date_debut),
    constraint ck_portefeuille_dates check (ptf_date_fin is null or ptf_date_fin >= ptf_date_debut)
);
-- Un praticien n'est suivi que par un seul visiteur à la fois
create unique index ux_portefeuille_en_cours
    on PORTEFEUILLE (case when ptf_date_fin is null then pra_num end);
create index ix_portefeuille_collab on PORTEFEUILLE (col_matricule);

-- ---------------------------------------------------------------------
-- 3. PRODUITS (médicaments)
-- ---------------------------------------------------------------------

create table FAMILLE (
    fam_code        varchar2(3 char)   constraint pk_famille primary key,
    fam_libelle     varchar2(80 char)  not null
);

create table MEDICAMENT (
    med_depot_legal             varchar2(10 char)   constraint pk_medicament primary key,
    med_nom_commercial          varchar2(50 char)   not null,
    fam_code                    varchar2(3 char)    not null
                                constraint fk_medicament_famille references FAMILLE (fam_code),
    med_effets                  varchar2(1000 char),
    med_contre_indic            varchar2(1000 char),
    med_prix_echantillon        number(8, 2)        not null,
    med_date_commercialisation  date,
    med_actif                   char(1)             default 'O' not null,
    constraint uq_medicament_nom  unique (med_nom_commercial),
    constraint ck_medicament_prix check (med_prix_echantillon >= 0),
    constraint ck_medicament_actif check (med_actif in ('O', 'N'))
);

create table COMPOSANT (
    cmp_code        varchar2(4 char)   constraint pk_composant primary key,
    cmp_libelle     varchar2(60 char)  not null
);

-- Composition : liste des composants et quantité
create table CONSTITUER (
    med_depot_legal varchar2(10 char)  not null
                    constraint fk_constituer_medicament references MEDICAMENT (med_depot_legal) on delete cascade,
    cmp_code        varchar2(4 char)   not null
                    constraint fk_constituer_composant references COMPOSANT (cmp_code),
    cst_quantite    number(10, 3)      not null,
    cst_unite       varchar2(10 char)  not null,
    constraint pk_constituer primary key (med_depot_legal, cmp_code),
    constraint ck_constituer_qte check (cst_quantite > 0)
);

-- Interactions médicamenteuses
create table INTERAGIR (
    med_perturbateur    varchar2(10 char)  not null
                        constraint fk_interagir_perturbateur references MEDICAMENT (med_depot_legal) on delete cascade,
    med_perturbe        varchar2(10 char)  not null
                        constraint fk_interagir_perturbe references MEDICAMENT (med_depot_legal) on delete cascade,
    itr_description     varchar2(500 char),
    constraint pk_interagir primary key (med_perturbateur, med_perturbe),
    constraint ck_interagir_distincts check (med_perturbateur <> med_perturbe)
);

create table PRESENTATION (
    pre_code        varchar2(3 char)   constraint pk_presentation primary key,
    pre_libelle     varchar2(40 char)  not null
);

create table DOSAGE (
    dos_code        varchar2(10 char)  constraint pk_dosage primary key,
    dos_quantite    number(10, 3)      not null,
    dos_unite       varchar2(10 char)  not null,
    constraint ck_dosage_qte check (dos_quantite > 0)
);

create table TYPE_INDIVIDU (
    tin_code        varchar2(3 char)   constraint pk_type_individu primary key,
    tin_libelle     varchar2(40 char)  not null
);

-- Posologie : quantité périodique par type d'individu, selon présentation et dosage
create table PRESCRIRE (
    med_depot_legal varchar2(10 char)  not null
                    constraint fk_prescrire_medicament references MEDICAMENT (med_depot_legal) on delete cascade,
    tin_code        varchar2(3 char)   not null
                    constraint fk_prescrire_individu references TYPE_INDIVIDU (tin_code),
    pre_code        varchar2(3 char)   not null
                    constraint fk_prescrire_presentation references PRESENTATION (pre_code),
    dos_code        varchar2(10 char)  not null
                    constraint fk_prescrire_dosage references DOSAGE (dos_code),
    prs_posologie   varchar2(200 char) not null,
    constraint pk_prescrire primary key (med_depot_legal, tin_code, pre_code, dos_code)
);

-- ---------------------------------------------------------------------
-- 4. COMPTES-RENDUS DE VISITE
-- ---------------------------------------------------------------------

create table MOTIF (
    mot_code        varchar2(6 char)   constraint pk_motif primary key,
    mot_libelle     varchar2(60 char)  not null,
    mot_ordre       number(2)          not null,
    mot_actif       char(1)            default 'O' not null,
    constraint ck_motif_actif check (mot_actif in ('O', 'N'))
);

create table RAPPORT_VISITE (
    rap_num                     number generated by default as identity constraint pk_rapport_visite primary key,
    -- Auteur du CR (toujours renseigné : plus de CR anonyme)
    col_matricule               varchar2(10 char)  not null
                                constraint fk_rapport_collab references COLLABORATEUR (col_matricule),
    -- Praticien titulaire du cabinet (celui pour lequel on présente)
    pra_num                     number             not null
                                constraint fk_rapport_praticien references PRATICIEN (pra_num),
    -- Personne réellement vue si c'est un remplaçant
    pra_num_remplacant          number
                                constraint fk_rapport_remplacant references PRATICIEN (pra_num),
    rap_date_visite             date               not null,
    mot_code                    varchar2(6 char)
                                constraint fk_rapport_motif references MOTIF (mot_code),
    rap_motif_autre             varchar2(200 char),
    rap_bilan                   varchar2(4000),
    -- Confiance du praticien dans les produits GSB (1 = faible ... 5 = très forte)
    rap_coef_confiance          number(1),
    rap_date_prochaine_visite   date,
    -- B = brouillon, V = validé (définitif, pris en compte dans les statistiques)
    rap_etat                    char(1)            default 'B' not null,
    rap_date_saisie             timestamp          default systimestamp not null,
    rap_date_modif              timestamp,
    rap_date_validation         timestamp,
    constraint ck_rapport_etat        check (rap_etat in ('B', 'V')),
    constraint ck_rapport_remplacant  check (pra_num_remplacant is null or pra_num_remplacant <> pra_num),
    constraint ck_rapport_confiance   check (rap_coef_confiance is null or rap_coef_confiance between 1 and 5),
    constraint ck_rapport_prochaine   check (rap_date_prochaine_visite is null or rap_date_prochaine_visite > rap_date_visite),
    -- « Autre » exige une précision ; les autres motifs n'en ont pas
    constraint ck_rapport_motif_autre check (
           (mot_code = 'AUTRE' and rap_motif_autre is not null)
        or (mot_code <> 'AUTRE' and rap_motif_autre is null)
        or  mot_code is null),
    -- Un CR validé est forcément complet
    constraint ck_rapport_complet check (
           rap_etat = 'B'
        or (mot_code is not null and rap_bilan is not null and rap_coef_confiance is not null))
);
create index ix_rapport_collab_date    on RAPPORT_VISITE (col_matricule, rap_date_visite);
create index ix_rapport_praticien_date on RAPPORT_VISITE (pra_num, rap_date_visite);
create index ix_rapport_remplacant     on RAPPORT_VISITE (pra_num_remplacant);

-- Produits présentés : 2 au maximum (ordre 1 ou 2, unique par rapport)
create table PRESENTER (
    rap_num         number             not null
                    constraint fk_presenter_rapport references RAPPORT_VISITE (rap_num) on delete cascade,
    med_depot_legal varchar2(10 char)  not null
                    constraint fk_presenter_medicament references MEDICAMENT (med_depot_legal),
    pst_ordre       number(1)          not null,
    constraint pk_presenter primary key (rap_num, med_depot_legal),
    constraint uq_presenter_ordre unique (rap_num, pst_ordre),
    constraint ck_presenter_ordre check (pst_ordre in (1, 2))
);

-- Échantillons offerts : à l'unité près, indépendants des produits présentés
create table OFFRIR (
    rap_num         number             not null
                    constraint fk_offrir_rapport references RAPPORT_VISITE (rap_num) on delete cascade,
    med_depot_legal varchar2(10 char)  not null
                    constraint fk_offrir_medicament references MEDICAMENT (med_depot_legal),
    off_quantite    number(4)          not null,
    constraint pk_offrir primary key (rap_num, med_depot_legal),
    constraint ck_offrir_qte check (off_quantite > 0)
);

-- Temps de saisie : chaque ouverture du formulaire de CR (création / modification)
-- est tracée pour pouvoir comptabiliser le temps de saisie si la direction le décide.
create table SESSION_SAISIE (
    ses_id          number generated by default as identity constraint pk_session_saisie primary key,
    rap_num         number             not null
                    constraint fk_session_rapport references RAPPORT_VISITE (rap_num) on delete cascade,
    col_matricule   varchar2(10 char)  not null
                    constraint fk_session_collab references COLLABORATEUR (col_matricule),
    ses_debut       timestamp          not null,
    ses_fin         timestamp          not null,
    constraint ck_session_dates check (ses_fin >= ses_debut)
);
create index ix_session_rapport on SESSION_SAISIE (rap_num);

-- ---------------------------------------------------------------------
-- 5. ÉCHANTILLONS : attributions mensuelles (saisies par le délégué)
-- ---------------------------------------------------------------------

create table DOTATION (
    dot_id              number generated by default as identity constraint pk_dotation primary key,
    col_matricule       varchar2(10 char)  not null
                        constraint fk_dotation_visiteur references COLLABORATEUR (col_matricule),
    med_depot_legal     varchar2(10 char)  not null
                        constraint fk_dotation_medicament references MEDICAMENT (med_depot_legal),
    -- Premier jour du mois concerné
    dot_mois            date               not null,
    dot_quantite        number(6)          not null,
    col_matricule_saisie varchar2(10 char) not null
                        constraint fk_dotation_saisie references COLLABORATEUR (col_matricule),
    dot_date_saisie     timestamp          default systimestamp not null,
    constraint uq_dotation unique (col_matricule, med_depot_legal, dot_mois),
    constraint ck_dotation_mois check (dot_mois = trunc(dot_mois, 'MM')),
    constraint ck_dotation_qte  check (dot_quantite > 0)
);

-- ---------------------------------------------------------------------
-- 6. COMMUNICATION : messages entre personnes ou vers un groupe
-- ---------------------------------------------------------------------

create table MESSAGE (
    msg_id              number generated by default as identity constraint pk_message primary key,
    col_expediteur      varchar2(10 char)  not null
                        constraint fk_message_expediteur references COLLABORATEUR (col_matricule),
    msg_objet           varchar2(100 char) not null,
    msg_contenu         varchar2(4000)     not null,
    msg_date_envoi      timestamp          default systimestamp not null
);

-- Un envoi à un groupe (région, secteur) crée une ligne par destinataire
create table MESSAGE_DESTINATAIRE (
    msg_id              number             not null
                        constraint fk_destinataire_message references MESSAGE (msg_id) on delete cascade,
    col_matricule       varchar2(10 char)  not null
                        constraint fk_destinataire_collab references COLLABORATEUR (col_matricule),
    dst_date_lecture    timestamp,
    constraint pk_message_destinataire primary key (msg_id, col_matricule)
);
create index ix_destinataire_collab on MESSAGE_DESTINATAIRE (col_matricule);

-- ---------------------------------------------------------------------
-- 7. SÉCURITÉ : journal des connexions
-- ---------------------------------------------------------------------

create table JOURNAL_CONNEXION (
    jco_id          number generated by default as identity constraint pk_journal_connexion primary key,
    jco_login       varchar2(30 char)  not null,
    col_matricule   varchar2(10 char)
                    constraint fk_journal_collab references COLLABORATEUR (col_matricule),
    jco_date        timestamp          default systimestamp not null,
    jco_succes      char(1)            not null,
    constraint ck_journal_succes check (jco_succes in ('O', 'N'))
);
create index ix_journal_date on JOURNAL_CONNEXION (jco_date);
